### ISSUE TITLE
[Feature Request] Support Updating Sub Labels

### ISSUE THREAD

**Issue by NickM-27** [mmcc-xx/WhosAtMyFeeder#11]
Frigate has [support for sub labels](https://docs.frigate.video/integrations/api#post-apieventsidsub_label) which show in the event list like `Person: Nick`. It would be awesome if this project could update the sub label for bird events with the type of bird that was detected. I'm happy to help with answering questions on the Frigate API side if you have any.

**Comment by mmcc-xx** [comment]
Hi Person: Nick -

Is it turns out I'm kind of overhauling this app to make better use of Frigate's events and storage. This would be a good time to implement such a thing. 

It looks straight forward enough... is it going to cause any problems if I change the sublabel after initially setting it? I'm looking at every snapshot change for a given event, and if a given snapshot provides a better identification confidence score, I toss the old one. So a given event might initially be identified as a Red Bellied Woodpecker, but then we get a better ID as a Norther Flicker.

Also, do you think using the common name or scientific name makes more sense. I'm thinking common name, but I could be dissuaded.

**Comment by NickM-27** [comment]
> It looks straight forward enough... is it going to cause any problems if I change the sublabel after initially setting it?

No, it can be set, updated, and even removed without issues. The only restriction and I doubt you would run into it is that there is a max length of 100 characters in the unreleased frigate 0.13 and a max length of 20 characters in the current 0.12.1 release. 

> Also, do you think using the common name or scientific name makes more sense. I'm thinking common name, but I could be dissuaded.

Sounds like something that could have a configuration option, but as a user I'd certainly prefer the common name

**Comment by mmcc-xx** [comment]
Cool! I'll truncate to 20 characters for now. Thanks for the heads up on that.

![image](https://github.com/mmcc-xx/WhosAtMyFeeder/assets/1315341/01d7c227-180c-47b4-9bae-b62f6f635221)

I should get the new version released in a day or two.
