### ISSUE TITLE
Home Assistant Addon Depreciated

### ISSUE THREAD

**Issue by nfmsh** [mmcc-xx/WhosAtMyFeeder#42]
Hello, the home assistant addon is showing as depreciated and not working? does anyone know of a repository with a working version ?
Thanks

**Comment by bertybuttface** [comment]
@IanC74 

Hello

The main thing is this app uses relative paths and Home Assistant doesn't like that. Someone needs to redo this addon but instead of monkey patching URLs like I was they need to do it properly by making the Home Assistant ingress rewrite the URLs as they need them. 

My addon can work as a base for that or you can simply start over. I'm happy to provide limited support to your endeavour but I'm very busy right now hence deprecating the addon vs fixing my shit technique.

It shouldn't be that hard, I just got the wrong end of the stick when I tried.

Cheers,

Good luck!

**Comment by bertybuttface** [comment]
I pushed version 1.1.0 give it a go and see if it solves your problems.

**Comment by nfmsh** [comment]
Hi just tried to run the upgrade via home assistant and I get this error 
Can't install ghcr.io/bertybuttface/amd64-addon-whosatmyfeeder:1.1.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=1.1.0&fromImage=ghcr.io%2Fbertybuttface%2Famd64-addon-whosatmyfeeder&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

Thanks

**Comment by nfmsh** [comment]
Sorry clicked the wrong button still getting used to Github

**Comment by bertybuttface** [comment]
Apologies the build system hadn't been updated in a while so it couldn't build 1.0.0

I have pushed out 1.1.1 which has built correctly and has some extra fixes.

Should all be working now. Might need to refresh (top right corner)

**Comment by nfmsh** [comment]
@bertybuttface 
Yes that's fixed it. 
Thanks

**Comment by bertybuttface** [comment]
Fantastic, let me know if you encounter any other bugs but if you could close this for now I'd appreciate it.
